#!/bin/bash
echo " "
echo " "
echo "Test 1:"
./a.out < ./Tests/Test1.txt
echo " "
echo " "
echo "Test 2:"
./a.out < ./Tests/Test2.txt
echo " "
echo " "
echo "Test 3:"
./a.out < ./Tests/Test3.txt
echo " "
echo " "
echo "Test 4:"
./a.out < ./Tests/Test4.txt
echo " "
echo " "
echo "Test 5:"
./a.out < ./Tests/Test5.txt
