#!/bin/bash

count=1
g++ -std=c++11 Source/main.cpp Source/otherfuncs.cpp

for((; count<6; count++))
do
    input="Test/test$count.txt"
    if [ -f $input ]
    then
        echo -e "";
    else
        echo "No such input file which named \"$input\"! Aborting!";
	exit 1
    fi
    echo "[Test#$count]: "
    ./a.out < $input
    echo "__________________________________________";
done > "output.txt" 2> "output.txt"
echo "All values calculated"
rm ./a.out


