#!/bin/bash

count=1
g++ -std=c++11 Source/hier_list.cpp Source/main.cpp

declare -a array
for((; count<16; count++))
do
    input="Test/test$count.txt"
    if [ -f $input ]
    then
        echo -e "";
    else
        echo "No such input file which named \"$input\"! Aborting!";
	exit 1
    fi
    echo "[Test#$count]: "
    ./a.out < $input
done
echo "All values calculated"
rm ./a.out


